server:
  port: 80
####服务网关名称
spring:
  application:
    name: gmall-gateway
  cloud:
    gateway:
#      ###路由策略
#      routes:
#      - id: member
#        ####转发http://www.gmall.com/
#        uri: lb://gmall-member/
#        ####匹配规则
#        predicates:
#        - Path=/member/**
#        filters:
#        - StripPrefix=1
      discovery:
        locator:
          ####允许通过注册中心获取地址调用
          enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849