server:
  port: 80
####服务网关名称
spring:
  application:
    name: gmall-gateway
  cloud:
    gateway:
      ###路由策略
      routes:
      - id: mayikt
        ####转发http://www.gmall.com/
        uri: http://www.mayikt.com/
        ####匹配规则
        predicates:
        - Path=/mayikt/**
        filters:
        - StripPrefix=1