spring:
  application:
    name: rocketmq-demo-bank2
  cloud:
    nacos:
      discovery:
        # nacos注册地址
        server-addr: 10.211.145.121:8849,10.211.145.121:8850,10.211.145.121:8851
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank2?useUnicode=true
    username: root
    password: 123456

server:
  port: 18081
  servlet:
    context-path: /bank2

rocketmq:
  producer:
    group: producer_bank2
  name-server: 127.0.0.1:9876