server:
  port: 8080

spring:
  application:
    name: gmall-member
  cloud:
    nacos:
      discovery:
        # nacos注册地址
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848



#gmall:
#  name: gmall电子商城